# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-31 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tether', '0002_remove_league_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='players',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
