# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-31 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tether', '0003_league_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='owner',
        ),
    ]
