# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-31 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tether', '0005_league_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='players',
        ),
    ]
