# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-22 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tether', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaguemembership',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='leaguemembership',
            name='league',
        ),
        migrations.RemoveField(
            model_name='leaguemembership',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='userprofile1',
            name='leagues',
        ),
        migrations.DeleteModel(
            name='LeagueMembership',
        ),
    ]
