# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-23 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tether', '0002_auto_20170422_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchplayers',
            name='player0_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayers',
            name='player2_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayers',
            name='player3_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayers',
            name='player4_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayers',
            name='player5_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayers',
            name='player6_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayers',
            name='player7_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayers',
            name='player8_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayers',
            name='player9_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
