# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-22 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tether', '0003_auto_20170421_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchplayers',
            old_name='p1ayer1_id',
            new_name='player1_id',
        ),
        migrations.RenameField(
            model_name='matchplayers',
            old_name='p1ayer2_id',
            new_name='player2_id',
        ),
        migrations.RenameField(
            model_name='matchplayers',
            old_name='p1ayer3_id',
            new_name='player3_id',
        ),
        migrations.RenameField(
            model_name='matchplayers',
            old_name='p1ayer4_id',
            new_name='player4_id',
        ),
        migrations.RenameField(
            model_name='matchplayers',
            old_name='p1ayer5_id',
            new_name='player5_id',
        ),
        migrations.RenameField(
            model_name='matchplayers',
            old_name='p1ayer6_id',
            new_name='player6_id',
        ),
        migrations.RenameField(
            model_name='matchplayers',
            old_name='p1ayer7_id',
            new_name='player7_id',
        ),
        migrations.RenameField(
            model_name='matchplayers',
            old_name='p1ayer8_id',
            new_name='player8_id',
        ),
        migrations.RenameField(
            model_name='matchplayers',
            old_name='p1ayer9_id',
            new_name='player9_id',
        ),
    ]
