# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-22 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tether', '0002_auto_20170421_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_skill', models.DecimalField(decimal_places=2, default='500', max_digits=6)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tether.League')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tether.UserProfile1')),
            ],
            options={
                'db_table': 'league_membership',
            },
        ),
        migrations.AddField(
            model_name='userprofile1',
            name='leagues',
            field=models.ManyToManyField(through='tether.LeagueMembership', to='tether.League'),
        ),
        migrations.AlterUniqueTogether(
            name='leaguemembership',
            unique_together=set([('profile', 'league')]),
        ),
    ]
