# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-23 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tether', '0004_auto_20170421_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile1',
            name='steam_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
