# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-18 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tether', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile1',
            name='leagues',
        ),
    ]
