# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-31 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tether', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile1',
            name='leagues',
            field=models.ManyToManyField(to='tether.League'),
        ),
    ]
