# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-18 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tether', '0002_remove_userprofile1_leagues'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile1',
            name='leagues',
            field=models.ManyToManyField(to='tether.League'),
        ),
    ]
