# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-19 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tether', '0003_userprofile1_leagues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile1',
            name='steam_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
