# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-30 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tether', '0004_auto_20170318_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentMatches',
        ),
    ]
