# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-22 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tether', '0005_auto_20170421_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='result',
            new_name='winner',
        ),
    ]
