# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-22 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tether', '0002_userprofile1_leagues'),
        ('tether', '0006_auto_20170421_1830'),
        ('tether', '0005_delete_recentmatches'),
    ]

    operations = [
    ]
